export const LIST_STUDENT_STARTED = 'LIST_STUDENT_STARTED';
export const LIST_STUDENT_SUCCESS = 'LIST_STUDENT_SUCCESS';
export const LIST_STUDENT_FAILURE = 'LIST_STUDENT_FAILURE';

export const ADD_STUDENT_STARTED = 'ADD_STUDENT_STARTED';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';

export const DELETE_STUDENT_STARTED = 'DELETE_STUDENT_STARTED';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';